sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install .[tensorflow-cpu]
  - pip install flake8

script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings. Texar limits lines to a maximum of 80 chars. 
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics
  # Unit tests
  - pytest

jobs:
  include:
    - stage: docs
      python: "3.6"
      install:
        - pip install --upgrade pip
        - pip install --progress-bar off -r requirements.txt
        - pip install --progress-bar off -r docs/requirements.txt
      script:
        - cd docs
        # Build documents
        - sphinx-build -b html -d _build/doctrees . _build/html

notifications:
  email: false
